### ISSUE TITLE
solr_wrapper attempts to create a collection when one already exists.

### ISSUE THREAD

**Issue by jcoyne** [cbeer/solr_wrapper#82] opened 2016-10-17 17:04 UTC
``
Starting Solr 6.2.0 on port 8983 ... /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/solr_wrapper-0.18.1/lib/solr_wrapper/instance.rb:356:in `exec': Failed to execute solr create:  (RuntimeError)
Connecting to ZooKeeper at localhost:9983 ...
Re-using existing configuration directory hydra-development

ERROR:
Collection 'hydra-development' already exists!
Checked collection existence using Collections API command:
http://localhost:8983/solr/admin/collections?action=list

	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/solr_wrapper-0.18.1/lib/solr_wrapper/instance.rb:154:in `create'
	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/solr_wrapper-0.18.1/lib/solr_wrapper/instance.rb:211:in `with_collection'
	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/solr_wrapper-0.18.1/exe/solr_wrapper:109:in `block in <top (required)>'
	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/solr_wrapper-0.18.1/lib/solr_wrapper/instance.rb:64:in `wrap'
	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/solr_wrapper-0.18.1/exe/solr_wrapper:108:in `<top (required)>'
	from /Users/jcoyne/.rbenv/versions/2.3.0/bin/solr_wrapper:23:in `load'
	from /Users/jcoyne/.rbenv/versions/2.3.0/bin/solr_wrapper:23:in `<main>'
```

**Comment by cbeer** [comment] 2016-10-17 17:15
Duplicate of #69?

**Closed** 2016-10-17 17:16 UTC
